# Project information
site_name: auto_fe Documentation
# defeine TOC or order of website-
nav:
  - Home: index.md

site_author: RAravindan
site_description: >-
  A library for auto feature engineering!

# Repository
repo_name: RAravindDS/auto_fe
repo_url: https://github.com/RAravindDS/auto_fe

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
  # logo: PyTorch_logo_icon.svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/RAravindDS
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aravindds/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark

plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/RAravindDS"  target="_blank" rel="noopener">R Aravindan</a>
